umask 077                   # Deny group/world rwx by default (multiuser systems)
setopt extended_glob
setopt prompt_subst         # Required for the prompt
setopt share_history        # Share history between multiple instances of zsh
setopt auto_list            # Show possible matches if completion can't figure out what to do
setopt auto_resume          # Commands without arguments will first try to resume suspended programs of the same name
setopt extended_history     # Put beginning and ending timestamps in the history file
setopt hist_ignore_dups     # Sequential duplicate commands only get one history entry
setopt hist_find_no_dups    # Don't show duplicate commands when searching the history
setopt magic_equal_subst    # Do completion on <value> in foo=<value>
setopt nonomatch            # Don't error if globbing fails; just leave the globbing chars in
setopt auto_cd              # Skip `cd` when changing to a directory
setopt no_beep              # "I refer to this informally as the OPEN_PLAN_OFFICE_NO_VIGILANTE_ATTACKS option."
export PAGER=less
setopt cdablevars           # Allow to have bookmarks with emacs(see bottom)

alias mktags='cd $1 && `find . -name "*.[h|c]"` | xargs etags && cd -'

zmodload zsh/complist
autoload -U compinit && compinit
zstyle ':completion:::::' completer _complete _approximate
zstyle -e ':completion:*:approximate:*' max-errors 'reply=( $(( ($#PREFIX + $#SUFFIX) / 3 )) )'
zstyle ':completion:*:descriptions' format "- %d -"
zstyle ':completion:*:corrections' format "- %d - (errors %e)"
zstyle ':completion:*:default' list-prompt '%S%M matches%s'
zstyle ':completion:*' group-name ''
zstyle ':completion:*:manuals' separate-sections true
zstyle ':completion:*:manuals.(^1*)' insert-sections true
zstyle ':completion:*' menu select
zstyle ':completion:*' verbose yes


# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#export ZSH_THEME="random"
export ZSH_THEME="fino"
# Consider "obraun"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want disable red dots displayed while waiting for completion
# DISABLE_COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx ruby ssh-agent heroku git-flow github pip)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/usr/texbin:/usr/X11/bin

# set term to 256 because pretty emacs is good emacs
export TERM=xterm-256color
export PYTHONPATH=/usr/lib/python2.6/site-packages/
alias ll='ls -l'
alias emacsclient='/usr/local/bin/emacsclient -n $@'
alias ec='emacsclient'
export EDITOR=/usr/local/bin/emacsclient-friendly
alias hgpush="printf '%s%s' 'hg push ssh://hg@bitbucket.org/mjsteger/' $1"
[[ -r ~/.zsh.bmk ]] && source ~/.zsh.bmk
PATH=$PATH:~/bin/
alias python32="arch -i386 /usr/bin/python2.6"
unset SSH_AUTH_SOCK
PATH=$PATH:/usr/texbin/


# source $HOME/.z/z.sh
export ZSH=$HOME/.oh-my-zsh

eval `ssh-agent`
# ssh-add ~/.ssh/id_rsa
eval "$(rbenv init -)"
PATH=$PATH:~/.cabal/bin/
alias b="bundle exec"
export DOCKER_HOST='tcp://192.168.33.42:2375'
export JRUBY_OPTS="--2.0 -J-Xmx4096m -J-XX:PermSize=512m -J-XX:MaxPermSize=512m"
alias eu4="~/Library/Application\ Support/Steam/SteamApps/common/Europa\ Universalis\ IV/eu4.app/Contents/MacOS/eu4"
export LPASS_AGENT_TIMEOUT=0
function rename_window() { echo -ne "\033]0;$1\007" }
DISABLE_AUTO_TITLE="true"
eval "$(direnv hook zsh)"
export GOPATH=/Users/steggy/gocode/
PATH=$PATH:${GOPATH}/bin
source ~/.secrets
